### ISSUE TITLE
Connector breaks after running through few tasks

### ISSUE THREAD

**Issue by roshan81** [mpieters3/ansible-eci-connector#2]
I configured Ansible to use this connector for my deployments. My playbook has many include_tasks to run in the node. It breaks after completing few tasks with the following error. Please help.

task path: /var/lib/jenkins/workspace/create-ami-using-instance-connect/SoftwareDeployment/tasks/installNewRelicApm.yml:7
NO PRIVATE KEY FILE, GENERATING ON DEMAND
TEMPORARY KEY LOCATION: /tmp/tmpYyVdBB
<10.211.135.217> ESTABLISH SSH CONNECTION FOR USER: ec2_user
ECI PUB KEY EXPIRING/NOT SENT, PUSHING NOW
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 146, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 645, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/normal.py", line 46, in run
    result = merge_hash(result, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 780, in _execute_module
    self._make_tmp_path()
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 346, in _make_tmp_path
    tmpdir = self._remote_expand_user(remote_tmp, sudoable=False)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 664, in _remote_expand_user
    data = self._low_level_execute_command(cmd, sudoable=False)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 1071, in _low_level_execute_command
    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/ssh.py", line 1192, in exec_command
    (returncode, stdout, stderr) = self._run(cmd, in_data, sudoable=sudoable)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/ssh.py", line 392, in wrapped
    return_tuple = func(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/ssh.py", line 1053, in _run
    return self._bare_run(cmd, in_data, sudoable=sudoable, checkrc=checkrc)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/eci.py", line 374, in _bare_run
    _push_key(self._get_boto_args(), self._get_eci_args())
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/eci.py", line 425, in _push_key
    client.send_ssh_public_key(**eci_args)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 276, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 586, in _make_api_call
    raise error_class(parsed_response, operation_name)
ThrottlingException: An error occurred (ThrottlingException) when calling the SendSSHPublicKey operation (reached max retries: 4): Server is busy! Please retry after a moment.
fatal: [10.211.135.217]: FAILED! => {}

**Comment by roshan81** [comment]
It worked! I missed configuring **retries** in my ansible.cfg earlier. Closing the issue. Thank you for the plugin!!
