### ISSUE TITLE
Does not work with Ansible 2.9

### ISSUE THREAD

**Issue by vinayvenu** [mpieters3/ansible-eci-connector#4]
This is an initial report, I will try getting more information. 

```
ansible --version
ansible 2.8.12
  config file = None
```

```
cat ./inventory
hostname.com ansible_connection=eci ansible_hostname=ubuntu
```

```
ansible -i ./inventory all -m ping -vvv
```

```
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/Cellar/ansible@2.8/2.8.12_2/libexec/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 145, in run
    res = self._execute()
  File "/usr/local/Cellar/ansible@2.8/2.8.12_2/libexec/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 606, in _execute
    self._connection = self._get_connection(variables=variables, templar=templar)
  File "/usr/local/Cellar/ansible@2.8/2.8.12_2/libexec/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 908, in _get_connection
    ansible_playbook_pid=to_text(os.getppid())
  File "/usr/local/Cellar/ansible@2.8/2.8.12_2/libexec/lib/python3.7/site-packages/ansible/plugins/loader.py", line 579, in get
    obj = obj(*args, **kwargs)
  File "/Users/vinay/.ansible/plugins/connection/eci.py", line 336, in __init__
    self.set_options()
  File "/usr/local/Cellar/ansible@2.8/2.8.12_2/libexec/lib/python3.7/site-packages/ansible/plugins/__init__.py", line 75, in set_options
    self._options = C.config.get_plugin_options(get_plugin_class(self), self._load_name, keys=task_keys, variables=var_options, direct=direct)
AttributeError: 'Connection' object has no attribute '_load_name'
```

I have tried with ansible 2.9.13 as well, with the same behavior.

**Comment by budgester** [comment]
I tried 

```
class Connection(ssh.Connection):
    """ SSH connection that uses EC2 Instance Connect to connect """

    transport = 'eci'
    has_pipelining = True

    def __init__(self, *args, **kwargs):
        ssh.Connection.__init__(self, *args, **kwargs)
        self._load_name = "eci"
        self.set_options()
```
and then a connection with specifying the username helped, unless this is already set in your ansible config

`ansible -i inventory all -m ping -vvv -u ubuntu`

**Comment by budgester** [comment]
https://github.com/mpieters3/ansible-eci-connector/pull/7 is a better fix than above

**Comment by mpieters3** [comment]
Should be resolved
