### ISSUE TITLE
Ansible throws error: Requested entry (plugin_type: connection plugin: eci setting: password ) was not defined in configuration.

### ISSUE THREAD

**Issue by syphernl** [mpieters3/ansible-eci-connector#5]
I'm trying to run this with Ansible 2.10.2 but when I use this connection plugin it fails because it appears that Ansible expects a password to be provided:

```
NO PRIVATE KEY FILE, GENERATING ON DEMAND
TEMPORARY KEY LOCATION: /tmp/tmpxn2xyq8e
<XX.XX.XX.XX> ESTABLISH SSH CONNECTION FOR USER: xxxxx
The full traceback is:
Traceback (most recent call last):
  File "/home/frank/.local/lib/python3.8/site-packages/ansible/plugins/__init__.py", line 58, in get_option
    option_value = C.config.get_config_value(option, plugin_type=get_plugin_class(self), plugin_name=self._load_name, variables=hostvars)
  File "/home/frank/.local/lib/python3.8/site-packages/ansible/config/manager.py", line 411, in get_config_value
    value, _drop = self.get_config_value_and_origin(config, cfile=cfile, plugin_type=plugin_type, plugin_name=plugin_name,
  File "/home/frank/.local/lib/python3.8/site-packages/ansible/config/manager.py", line 524, in get_config_value_and_origin
    raise AnsibleError('Requested entry (%s) was not defined in configuration.' % to_native(_get_entry(plugin_type, plugin_name, config)))
ansible.errors.AnsibleError: Requested entry (plugin_type: connection plugin: eci setting: password ) was not defined in configuration.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frank/.local/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 158, in run
    res = self._execute()
  File "/home/frank/.local/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 663, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/frank/.local/lib/python3.8/site-packages/ansible/plugins/action/gather_facts.py", line 86, in run
    res = self._execute_module(module_name=fact_module, module_args=mod_args, task_vars=task_vars, wrap_async=False)
  File "/home/frank/.local/lib/python3.8/site-packages/ansible/plugins/action/__init__.py", line 826, in _execute_module
    self._make_tmp_path()
  File "/home/frank/.local/lib/python3.8/site-packages/ansible/plugins/action/__init__.py", line 388, in _make_tmp_path
    tmpdir = self._remote_expand_user(self.get_shell_option('remote_tmp', default='~/.ansible/tmp'), sudoable=False)
  File "/home/frank/.local/lib/python3.8/site-packages/ansible/plugins/action/__init__.py", line 709, in _remote_expand_user
    data = self._low_level_execute_command(cmd, sudoable=False)
  File "/home/frank/.local/lib/python3.8/site-packages/ansible/plugins/action/__init__.py", line 1121, in _low_level_execute_command
    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/home/frank/.local/lib/python3.8/site-packages/ansible/plugins/connection/ssh.py", line 1222, in exec_command
    cmd = self._build_command(*args)
  File "/home/frank/.local/lib/python3.8/site-packages/ansible/plugins/connection/ssh.py", line 568, in _build_command
    conn_password = self.get_option('password') or self._play_context.password
  File "/home/frank/.local/lib/python3.8/site-packages/ansible/plugins/__init__.py", line 60, in get_option
    raise KeyError(to_native(e))
KeyError: 'Requested entry (plugin_type: connection plugin: eci setting: password ) was not defined in configuration.'
fatal: [XX.XX.XX.XX]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}

```

Might be related to #4, since it could not be compatible with Ansible versions past 2.8.x?

**Comment by mpieters3** [comment]
@syphernl  - is this working now for you?

**Comment by pcamelo** [comment]
This issue persists in ansible 2.10.7:

```
The full traceback is:
Traceback (most recent call last):
  File "/var/tmp/ansible_deployment/lib/python3.7/site-packages/ansible/plugins/__init__.py", line 58, in get_option
    option_value = C.config.get_config_value(option, plugin_type=get_plugin_class(self), plugin_name=self._load_name, variables=hostvars)
  File "/var/tmp/ansible_deployment/lib/python3.7/site-packages/ansible/config/manager.py", line 427, in get_config_value
    keys=keys, variables=variables, direct=direct)
  File "/var/tmp/ansible_deployment/lib/python3.7/site-packages/ansible/config/manager.py", line 539, in get_config_value_and_origin
    raise AnsibleError('Requested entry (%s) was not defined in configuration.' % to_native(_get_entry(plugin_type, plugin_name, config)))
ansible.errors.AnsibleError: Requested entry (plugin_type: connection plugin: eci setting: password ) was not defined in configuration.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/tmp/ansible_deployment/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 158, in run
    res = self._execute()
  File "/var/tmp/ansible_deployment/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 663, in _execute
    result = self._handler.run(task_vars=variables)
  File "/var/tmp/ansible_deployment/lib/python3.7/site-packages/ansible/plugins/action/command.py", line 26, in run
    results = merge_hash(results, self._execute_module(module_name='ansible.legacy.command', task_vars=task_vars, wrap_async=wrap_async))
  File "/var/tmp/ansible_deployment/lib/python3.7/site-packages/ansible/plugins/action/__init__.py", line 826, in _execute_module
    self._make_tmp_path()
  File "/var/tmp/ansible_deployment/lib/python3.7/site-packages/ansible/plugins/action/__init__.py", line 388, in _make_tmp_path
    tmpdir = self._remote_expand_user(self.get_shell_option('remote_tmp', default='~/.ansible/tmp'), sudoable=False)
  File "/var/tmp/ansible_deployment/lib/python3.7/site-packages/ansible/plugins/action/__init__.py", line 709, in _remote_expand_user
    data = self._low_level_execute_command(cmd, sudoable=False)
  File "/var/tmp/ansible_deployment/lib/python3.7/site-packages/ansible/plugins/action/__init__.py", line 1121, in _low_level_execute_command
    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/var/tmp/ansible_deployment/lib/python3.7/site-packages/ansible/plugins/connection/ssh.py", line 1222, in exec_command
    cmd = self._build_command(*args)
  File "/var/tmp/ansible_deployment/lib/python3.7/site-packages/ansible/plugins/connection/ssh.py", line 568, in _build_command
    conn_password = self.get_option('password') or self._play_context.password
  File "/var/tmp/ansible_deployment/lib/python3.7/site-packages/ansible/plugins/__init__.py", line 60, in get_option
    raise KeyError(to_native(e))
KeyError: 'Requested entry (plugin_type: connection plugin: eci setting: password ) was not defined in configuration.'
fatal: [(redacted)]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```
